name: GH Pages
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  pages:
    name: Build files for GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Generate schemas
        uses: docker://ghcr.io/sysbot-org/tgscraper
        with:
          args: "app:export-schema --readable ${{ github.workspace }}/botapi.json"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: schemas
          publish_branch: gh-pages
          cname: tgscraper.sys001.ml
          enable_jekyll: true